### ISSUE TITLE
Issue with custom functions compatible with existing com Add-in 

### ISSUE THREAD

**Issue by vikasm1720** [OfficeDev/Excel-Custom-Functions#220] opened 2020-07-06 12:31 UTC
I have existing custom function created in Com Add-in. To support MAC and online I am creating a web Add-in. I have included the equivalent add-in in the manifest. but the web add-in does not recognize the custom function created in com add-in when the same workbook opened on browser/mac instead, it throws #Name? and displays the namespace used in com add-in. 

  <EquivalentAddins>
    <EquivalentAddin>
      <ProgId>xxx.Office.Formulas</ProgId>
      <Type>COM</Type>
    </EquivalentAddin>
  </EquivalentAddins>

Custom function used in com Add-in template "=get("data").
Custom function displayed on Browser "=@xxx.Office.Formulas.get("data")"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01562c5-ae22-8345-83f5-c1159bbb7cf0
* Version Independent ID: 70835436-060e-807f-3cee-a8ca0f7b6959
* Content: [Make your Office Add-in compatible with an existing COM add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in)
* Content Source: [docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment] 2020-07-06 17:32
@RuoyingLiang can you have a look at this? Thank you!

**Comment by lindalu-MSFT** [comment] 2020-07-09 01:17
@vikasm1720 Hi, I assigned this to our Excel team to triage. Meanwhile, can you provide us exact repro steps, screenshots, error msgs, as well as your manifest. THANKS! You can attach files to a message by dragging and dropping.

**Comment by vikasm1720** [comment] 2020-07-09 12:57
[addin.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/4896910/addin.zip)
Please find the attached screenshots and manifest.

**Comment by vikasm1720** [comment] 2020-07-09 12:59
[Addin.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/4896936/Addin.zip)
Please find the attached screenshots and manifest.

**Comment by xiaochunms** [comment] 2020-07-14 05:22
Looks like the CF is not installed for Web Add-in. You may can try to remove the whole EquivalentAddins node from manifest file and see if the CF can be recognized by Web-Addin without EquivalentAddins node.

**Comment by vikasm1720** [comment] 2020-07-14 05:45
CF is installed on Web Add-in and if I remove the "xxx.Office.Formulas." from the formula, the CF gets detected and fetches data. I have tried removing the node from the manifest file too, but it does not get detected unless I edit the formula and remove "xxx.Office.Formulas." from it.

**Comment by xiaochunms** [comment] 2020-07-14 06:24
It is the expected behavior for Custom Functions for XLL compatible mode. In Custom Functions XLL compatible mode, the Name follows the convention of XLL's functions, for example, no Namespace supported. 

In your case, if you treat "xxx.Office.Formulas" as the Namespace, it explains everything. 

If the EquivalentAddins node removed from the manifest file, it is a regular Web Add-in then. As Namespace is supported in this case, you can call the function by "=xxx.Office.Formulas.get("data")". 

But with the EquivalentAddins node, it is a Custom Functions XLL compatible mode Web Add-in. As Namespace is not supported in this case, you need to call the function by "=get("data")" then.

**Comment by vikasm1720** [comment] 2020-07-28 07:23
Thank you @xiaochunms, I understood the behaviour of custom functions. But Equivalent Addins node mentioned in the manifest file does not work as expected. 
As mentioned above I have com add-in and I installed the web add-in in Excel desktop. Since I have mentioned equivalent add-in in the manifest ideally I should not see web add-in right? according to documentation COM add-in takes priority and web add-in will not be visible but in my case, I see both add-ins visible in excel desktop version and web add-in takes priority.

       <EquivalentAddins>
		<EquivalentAddin>
			<ProgId>Contoso.Office.AutomationFormulas</ProgId>
			<Type>COM</Type>
		</EquivalentAddin>
	</EquivalentAddins>
  </VersionOverrides>
</OfficeApp>

**Comment by keyur32** [comment] 2020-07-30 01:25
I think you're missing the XLL Compatible tag here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf.  You can put a generic file name in there, as it is just mentioned to make it more identifiable.  This will cause your functions to save in XLL Compatible mode, internally the same way XLL Functions were written out as (=xll.<FunctionName>.

**Comment by vikasm1720** [comment] 2020-08-17 07:53
Hi @keyur32 , thank you for the info, this kind of solved half of my problem. this is what is happening now. I create a workbook with web add-in(Office online) and I have mentioned the XLL tag, after fetching data it does an autosave, Now I open the workbook on windows Desktop excel(com addin with same custom function name), I do not see any prefix like xlfudf_ to my custom functions, but they fail to refresh automatically, I need to a double click on the cell which has the formula and then press enter to force the recalculation. Do you know any way I can avoid this? I did try streaming Functions, same behaviour. also, i see an error on excel for windows, this add-in could not be started. close this dialog to ignore the problem or click restart to try again

**Comment by keyur32** [comment] 2020-08-17 14:15
Hi there, did you set the @volatile flag? That will force the functions to recalculate on open.

For the addin could not be started error with a streaming functions — we would like to investigate. Can you log a seperate issue for that please?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vikasm1720** [comment] 2020-08-17 14:41
Setting @volatile flag would recalculate all cells, each time I insert a new formula or modify an existing formula right? 
@volatile flag would solve my issue to recalculate when I open the workbook in com add-in, but for web add-in, it would create problems because modifying a particular cell would force recalculate entire worksheet, which I do not want to happen.

**Comment by ElizabethSamuel-MSFT** [comment] 2020-09-28 20:58
@keyur32 Any update on this? Thx.

**Comment by millerds** [comment] 2021-08-10 21:22
@vikasm1720 are you still having trouble?
@keyur32  are you still helping this person?

This doesn't look like a problem with the code in this repo, but rather challenges in coding specific behavior.  Closing now.  If you feel it needs more attention please reopen.

**Closed by millerds** 2021-08-10 21:22 UTC
Labels: Needs: attention :wave:, Type: programming question
