### ISSUE TITLE
Evaluating 3000 functions with 254 values each gets stuck on #BUSY

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/Excel-Custom-Functions#233] opened 2020-09-21 22:01 UTC
# Expected behavior

The values of the functions should appear

# Current behavior

When I evaluate 3000 functions at once, with each return value being an array of 254 numbers, the functions stay on #BUSY! and an error appears in the browser log:
> excel.officeapps.live.com/x/_vti_bin/EwaInternalWebService.json/ExecuteRichApiRequest?waccluster=PUS4:1 Failed to load resource: the server responded with a status of 500 ()

## Steps to Reproduce

1. In ScriptLab, load this gist: https://gist.github.com/fds-ssg/226fc6532483772c6085ddd801857966
2. Enter the formula `=SCRIPTLAB.TEST254.TEST254()` in cells A1:A3000
3. #BUSY! appears in each cell
4. After a while, the error noted above appears

## Context

* Excel 365 on the web in Chrome

## Failure Logs

Error from browser log with full call stack:
[temp.txt](https://github.com/OfficeDev/Excel-Custom-Functions/files/5258355/temp.txt)

**Comment by grangeryy** [comment] 2020-09-23 06:16
The request exceeds the limit of payload size in excel online due to large data sets. We have a feature in backlog for next Quarter to address this issue. Thx!

**Comment by grangeryy** [comment] 2021-03-18 02:25
The issue is now been fixed with the new feature rolling out.

**Closed by grangeryy** 2021-03-18 02:25 UTC
Labels: Status: in backlog, Type: product bug
