### ISSUE TITLE
Custom Function Auth Bearer Token POST requests do not work

### ISSUE THREAD

**Issue by adammpolak** [OfficeDev/Excel-Custom-Functions#351] opened 2022-11-12 20:53 UTC
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- v16 node (v18 does not work using yo generator and I've made an issue)
- There is no documentation on making a post request in a custom function
- Yes

# Expected behavior

Be able to make a post request and return data using a custom function.

# Current behavior

- I have made an authenticated POST request in taskpane.js and it works fine
- I make the exact same authenticated POST request in functions.js and it does not work
- I am using shared runtime and used the generator to create the project

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

The POST function (same issue with any POST function)

```
/**
 * Asks a server a question
 * @customfunction
 * @return returns a question.
 */

export async function ask() {
  const betterUrl = "https://api.openai.com/v1/completions";
  let data = {
    prompt: "what is the capital of france?",
    temperature: 0.7,
    max_tokens: 256,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    model: "text-davinci-002"
  };
  let xhttp = new XMLHttpRequest();
  return new Promise(function (resolve, reject) {
    xhttp.onreadystatechange = function() {
      if (xhttp.readyState !== 4) return;
      if (xhttp.status == 200) {
        resolve(JSON.stringify(JSON.parse(xhttp.responseText)));
      } else {
        reject({
          status: xhttp.status,

          statusText: xhttp.statusText,
        });
      }
    };
    xhttp.open("POST", betterUrl, true);
    xhttp.setRequestHeader("Authorization", "Bearer KEY");
    // xhttp.setRequestHeader("Content-Type", "application/json");
    xhttp.send(JSON.stringify(data));
  });
}
```
This same function works in taskpane.js ^

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Latest
* Node version: v16
* Office version: Latest
* Tool version: Latest

## Failure Logs

 xttp.readyState: 1	
 xttp.readyState: 4

It never goes to 2 to 3

**Comment by adammpolak** [comment] 2022-11-12 21:11
https://github.com/OfficeDev/Excel-Custom-Functions/issues/160

It seems like this issue was never answered ^

I am making an authenticated POST call in a custom function, is that "allowed"?

**Comment by RuizhiSunMS** [comment] 2022-11-14 05:56
@JHJ-MS

**Comment by adammpolak** [comment] 2022-11-14 14:34
To be clear, the request works from taskpane.js, but does not work in functions.js

I tried "calling" the function from taskpane.js but that doesn't work either.

**Comment by adammpolak** [comment] 2022-11-15 13:59
@JinghuiMS @RuizhiSunMS following up ^

**Comment by adammpolak** [comment] 2022-11-17 15:08
@JHJ-MS following up ^

**Comment by adammpolak** [comment] 2022-11-18 16:25
@JHJ-MS  ^

**Comment by adammpolak** [comment] 2022-11-21 15:50
@JHJ-MS ^

**Comment by celluj34** [comment] 2022-11-22 20:10
Does it work if you use `fetch` instead of `XMLHttpRequest`?

**Comment by adammpolak** [comment] 2022-11-28 00:25
> Does it work if you use `fetch` instead of `XMLHttpRequest`?

No, I've tried both.

Both fetch and xmlhttprequest work as GETs though (with no headers).

**Comment by davidchesnut** [comment] 2022-11-28 19:14
Hi @adammpolak, I'd run something like Fiddler to see the actual HTTPS POST requests over the network and compare the one that works to the one that fails. There must be some difference there that might help. Also maybe I'm missing it, but I don't see in your xhttp request where you set the auth token (or is this a different auth mechanism?)

Cheers,
David

**Comment by adammpolak** [comment] 2022-11-29 15:00
> 

@davidchesnut 
```    xhttp.open("POST", betterUrl, true);
    xhttp.setRequestHeader("Authorization", "Bearer KEY");
    // xhttp.setRequestHeader("Content-Type", "application/json");```
    
    That is where the headers are set ^

If I am using the exact same function in Taskpane.js and not in Functions.js and it works, then clearly it is not the function.

It is how excel treats POSTS from custom functions. This requires input from MSFT.

**Comment by adammpolak** [comment] 2022-11-29 15:00
@JHJ-MS ^

**Comment by davidchesnut** [comment] 2022-11-29 18:16
Sorry, I didn't catch that "KEY" is the token. Okay, I'll ping @JHJ-MS as well and some other folks to take a look at this. Thanks!

**Comment by adammpolak** [comment] 2022-12-06 20:03
> Sorry, I didn't catch that "KEY" is the token. Okay, I'll ping @JHJ-MS as well and some other folks to take a look at this. Thanks!

thank YOU!

**Comment by davidchesnut** [comment] 2022-12-06 22:12
Hi @adammpolak,

Out of curiosity if you add console.log statements, do they output to the browser console? If shared runtime is working, they should. If not the custom function is running in a separate JS runtime. This would help us narrow down if the issue is related to shared runtime config, or something else. Thanks!

**Comment by adammpolak** [comment] 2022-12-08 13:24
> Hi @adammpolak,
> 
> Out of curiosity if you add console.log statements to the custom function, do they output to the browser console? If shared runtime is working, they should. If not the custom function is running in a separate JS runtime. This would help us narrow down if the issue is related to shared runtime config, or something else. Thanks!

Great question!

No they do not, they go to the log file, which I just have open in VSCode and use as my "browser console".

I chose the shared runtime using the Yo generator, and I didn't do any funny business with the manifest after created the initial project using the generator.

I am on Windows 10 Enterprise OS Build 19044.2251 and running Excel Desktop

**Comment by adammpolak** [comment] 2022-12-09 14:59
> 

Nice!

**Comment by davidchesnut** [comment] 2022-12-12 16:54
Did that work?

**Comment by adammpolak** [comment] 2022-12-13 15:28
Sorry for delay in reply. I removed all the custom functions in my add in to use the task pane, so I have to get it all set up again. Will report back asap.

**Comment by adammpolak** [comment] 2022-12-13 20:30
> Did that work?

Now it won't open at all when I make that change after I make a new project using `yo office`

![image](https://user-images.githubusercontent.com/12940507/207437252-bdb3d17e-df51-4812-bae1-d28b78ed2ca2.png)

**Comment by davidchesnut** [comment] 2022-12-14 19:01
Hi @adammpolak,

I encounter this error a lot with the custom function projects. Usually you just need to [clear the cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache).

Also I was consulting with the team on this and discovered there is a bug in the yo office template where the resid in the manifest doesn't match. This will cause the custom functions to load in a JS-only runtime (not shared.) To fix this go in the manifest and make sure these two sections are using the exact same resid.

```xml
<Action xsi:type=”ShowTaskpane”>
  <SourceLocation resid="Taskpane.Url" />
</Action>
...
<Page>
  <SourceLocation resid="Taskpane.Url"/>
</Page>
```  

We're working to update the yo office template to use this in the manifest.

**Comment by adammpolak** [comment] 2022-12-14 19:52
Thank you!

**Comment by nkkinariwala** [comment] 2023-01-18 00:50
@adammpolak - did it work for you? Can you please provide the latest update?
@davidchesnut - did you get a chance to update office template as you mentioned?

**Comment by davidchesnut** [comment] 2023-01-18 22:58
This should be fixed today. See https://github.com/OfficeDev/Excel-Custom-Functions-JS/pull/94 Thanks!

**Comment by adammpolak** [comment] 2023-01-21 15:12
Thank you!

**Closed** 2023-02-06 16:50 UTC
Labels: Area: Excel, Type: product question
