### ISSUE TITLE
cannot run Excel Custom Functions

### ISSUE THREAD

**Issue by ShellyShulei** [OfficeDev/Excel-Custom-Functions#193] opened 2019-12-13 15:46 UTC
I cannot run my custom functions in the desktop excel, even sample applications don't work too. But when I use online Office365, everything is okay. Why?

**Comment by ShellyShulei** [comment] 2019-12-13 15:48
* I use excel add-in scriptlab

**Comment by Reezaali** [comment] 2019-12-19 02:36
Hello @ShellyShulei. I'm sorry to hear that this isn't working as expected. Can you include the steps you took so that I can reproduce the error? Can you provide the following information on your environment please? 

Platform [PC desktop, Mac, iOS, Office Online]: 
Office version number: 
Operating System: 
Browser (if using Office Online): 

Thank you.

**Comment by ShellyShulei** [comment] 2019-12-19 04:07
Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
Office version number: My excel version is 1912(Build 12325.20172 Monthly Channel(targeted)
And it's a business account which has Microsoft Office365 ProPlus subscription

Operating System: Win10

Failure Logs:
Error:
{
"description": "The argument is invalid or missing or has an incorrect format.",
"message": "The argument is invalid or missing or has an incorrect format.",
"name": "RichApi.Error",
"code": "InvalidArgument",
"traceMessages": [],
"innerError": null,
"debugInfo": {
"code": "InvalidArgument",
"message": "The argument is invalid or missing or has an incorrect format.",
"errorLocation": "CustomFunctionManager.register",
"statement": "v.register(...);",
"surroundingStatements": [
"var workbook=context.workbook;",
"var v=Microsoft.ExcelServices.CustomFunctionManager.newObject();",
"// >>>>>",
"v.register(...);",
"// <<<<<"
],
"fullStatements": [
"Please enable config.extendedErrorLogging to see full statements."
]
},
"stack": "InvalidArgument: The argument is invalid or missing or has an incorrect format.\n at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:24:283976)\n at o (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:3080913)\n at Anonymous function (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:3081060)\n at c (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:2415424)"
}

**Actually,** it worked well on 12/13/2019, then always show this error.
By the way, how can I delete my custom functions? I tried to uninstall my office365 and reinstalled it. Custom functions I have created before are still there.

**Comment by Reezaali** [comment] 2019-12-19 17:51
Hi @ShellyShulei, thanks for the additional information. Can you also include the steps to repro the issue please? Thank you.

**Comment by ShellyShulei** [comment] 2019-12-19 18:17
It will show one or more add-ins failed to install custom functions.
I just use the Script Lab inside the excel and run the sample of custom functions, it shows the error.
You can see these functions I have created before, I can use them on 12/13/2019.
![unnamed](https://user-images.githubusercontent.com/42678283/71198441-cb86c280-2261-11ea-8e65-a90d788f9f0a.jpg)
![Capture](https://user-images.githubusercontent.com/42678283/71198463-d3defd80-2261-11ea-80bc-be47296e8775.PNG)
![Capture1](https://user-images.githubusercontent.com/42678283/71198464-d3defd80-2261-11ea-919c-4f5c4224919c.PNG)
![Capture2](https://user-images.githubusercontent.com/42678283/71198465-d4779400-2261-11ea-977b-97eafa97cdb5.PNG)

**Comment by lindalu-MSFT** [comment] 2020-01-24 17:50
Hi @Reezaali @RuoyingLiang Is there any traction on this? I'm posting this comment to inquire so the bot doesn't mark it as "stale" now that it has been a month since this issue has had any activity. Please LMK if there's a resolution!

**Comment by Nova38** [comment] 2020-01-28 18:31
I am also having an identical issue. The yo genorated code gives an error but scriptlab works.

**Comment by mscharlock** [comment] 2020-02-03 18:54
Hi @Nova38 and @ShellyShulei - Have either of you tried clearing the WEF cache? Occasionally I run into a "fail to install Custom Functions" error like the one you are referencing and this usually clears it up for me (usually this is due to naming conflict). It will also get rid of custom functions you have created in the past.

**Comment by Nova38** [comment] 2020-02-03 19:21
@mscharlock I have not tried clearing the WEF cache. I will do so when i get the chance and let you all know if that resolves the issue. However the error occurred on the first time it was run so I don't exactly see how it could be a naming conflict.

**Comment by mscharlock** [comment] 2020-02-12 19:49
That does make sense, definitely not a naming thing then. I will go ahead and tag @nokafor - do you happen to know who the PM for Script Lab is at the moment? There is an error for @Nova38. Thanks!

**Comment by shyambhiogade** [comment] 2020-03-14 22:03
we are still getting this eror, is there any action done for this issue

**Comment by TCourtneyOwen** [comment] 2020-03-15 16:39
@shyambhiogade Sorry to hear you are having problems. Can you please try the following:

- Go to %:\Users\<user_name>\AppData\Local\Microsoft\Office\16.0\Wef
- Delete all the content in the WEF folder
- Return to your custom functions folder and run "npm run build" and "npm start" again.

Hopefully this helps.  Please keep us posted.

Thanks,

Courtney

**Comment by georgek01** [comment] 2020-03-26 05:31
Has this issue been resolved? Any custom function I run after creating the add-in using yo office, results in #BUSY! Launching the add-in from VS Code also results in an error being displayed in the Task pane.

<img width="290" alt="O365-Excel-Error" src="https://user-images.githubusercontent.com/19200702/77613595-f33ba400-6f8f-11ea-9098-0e25a1d972d0.PNG">

**Comment by TCourtneyOwen** [comment] 2020-03-26 15:02
@georgek01 The fact that the taskpane doesn't work either makes it seem like the dev-server didn't start.  Can you please try the following:

- Close Excel and stop the dev-server if it is in fact running
- From your project root, run "npm run build"
- Run "npm start"

At the very least the taskpane should work using the above steps, and I am hopeful this fixes the issue with custom functions as well.

-Courtney

**Comment by TCourtneyOwen** [comment] 2020-03-26 15:03
One other thing to try, can you please run "npx office-addin-dev-certs install" to ensure dev server certificates are installed

**Comment by georgek01** [comment] 2020-03-26 23:18
@TCourtneyOwen I followed the steps you suggested with no success.

<img width="306" alt="O365-Excel-Error-2" src="https://user-images.githubusercontent.com/19200702/77704776-b8368080-7022-11ea-973c-f37db790dbe6.PNG">

In the status bar I have the following message:

<img width="369" alt="O365-Excel-Error-3" src="https://user-images.githubusercontent.com/19200702/77704940-3004ab00-7023-11ea-9c49-f9d6a7ef827d.PNG">

But this message never changes.

Office Version : 18.2002.1101.0 (Office 365 Home Edition)
OS Version: 1909 (Build 18363.720)
Node Version: 10.14.2

**Comment by TCourtneyOwen** [comment] 2020-03-26 23:44
@georgek01 Just to clarify, have you had any luck with this add-in in the past, or has it been a problem from the moment you created it?

One other thing worth trying as noted above:

Go to %:\Users<user_name>\AppData\Local\Microsoft\Office\16.0\Wef
Delete all the content in the WEF folder
Return to your custom functions folder and run "npm run build" and "npm start" again

**Comment by georgek01** [comment] 2020-03-26 23:50
@TCourtneyOwen  This is the first add-in I'm creating.

I do not have a Wef folder at that location, so I clear it from the following registry key:

`HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Wef\Developer`

<img width="647" alt="reg-1" src="https://user-images.githubusercontent.com/19200702/77707258-7ceb8000-7029-11ea-8517-b0a238fb2704.PNG">

**Comment by TCourtneyOwen** [comment] 2020-03-26 23:56
Also did you choose to create a Typescript of Javascript project? I'd like to see if I can repro the problem locally

**Comment by georgek01** [comment] 2020-03-26 23:57
@TCourtneyOwen I found the folder and cleared it, but still experience the same issue after a build and run.

Path on my machine:
`C:\Users\georg\AppData\Local\Packages\Microsoft.Office.Desktop_8wekyb3d8bbwe\LocalCache\Local\Microsoft\Office\16.0`

**Comment by georgek01** [comment] 2020-03-26 23:57
I chose JavaScript.

**Comment by TCourtneyOwen** [comment] 2020-03-26 23:59
Are you able to browse to https://localhost:3000/taskpane.html after start the dev-server without getting any SSL cert warnings? If not, then this might be the problem that the dev-certs are not getting installed properly

**Comment by georgek01** [comment] 2020-03-27 00:04
No cert warnings.

<img width="808" alt="0365-task-panel-1" src="https://user-images.githubusercontent.com/19200702/77707902-6d6d3680-702b-11ea-9804-c544b27eedb4.PNG">

**Comment by TCourtneyOwen** [comment] 2020-03-27 00:07
Interesting, your's looks different than mine:
![image](https://user-images.githubusercontent.com/38081557/77708071-44de3180-6f84-11ea-82d7-9bf549caa46a.png)

**Comment by georgek01** [comment] 2020-03-27 00:08
Oh yes, I edited the HTML and removed the logo.

**Comment by georgek01** [comment] 2020-03-27 00:10
I can start a new add-in and not change anything if you like?

**Comment by TCourtneyOwen** [comment] 2020-03-27 00:10
@georgek01 I know this might be a pain, but would you be willing to create another project with yo office (e.g. the Office Addin Taskpane project) and see if that works? That might help us understand if the issue you are seeing (which I can't repro) is isolated to the custom functions project

**Comment by georgek01** [comment] 2020-03-27 00:11
Certainly! Will let you know shortly...

**Comment by georgek01** [comment] 2020-03-27 00:16
Received the following error I haven't seen before:

<img width="812" alt="yo-1" src="https://user-images.githubusercontent.com/19200702/77708460-0b153580-702d-11ea-8a05-2343d40fc202.PNG">

Going to try again...

**Comment by TCourtneyOwen** [comment] 2020-03-27 00:19
Ugh.. I wonder if that's related to network issues. Things have been a bit dicey over the past couple weeks it seems for obvious reasons

**Comment by georgek01** [comment] 2020-03-27 00:27
That all worked just fine

<img width="441" alt="yo-7" src="https://user-images.githubusercontent.com/19200702/77709025-a22ebd00-702e-11ea-8e68-da1250c4487d.PNG">

**Comment by TCourtneyOwen** [comment] 2020-03-27 00:34
Looping  a couple other folks: @akrantz @keyur32 Is there any particular Office build version that customers need to be running for Custom Functions to work? @georgek01  is running Office **Version : 18.2002.1101.0 (Office 365 Home Edition)** and he can't get Custom Functions to work using our Javascript template. He was however able to get the Office Addin Taskpane template working

**Comment by georgek01** [comment] 2020-03-27 00:44
I created another add-in for custom functions, cleared the wef folder and reg keys. Build succeeded and run started Excel as expected.

The same error then appears
<img width="439" alt="o365-yo-4" src="https://user-images.githubusercontent.com/19200702/77709709-d1462e00-7030-11ea-9289-aadfa58f1f07.PNG">

When I click the Show Taskpane button in the ribbon, the add-in displays, but none of the custom functions work
<img width="747" alt="o365-yo-5" src="https://user-images.githubusercontent.com/19200702/77709770-f89cfb00-7030-11ea-9bc4-8f549a6716e9.PNG">

**Comment by georgek01** [comment] 2020-03-27 00:49
Excel does now say the add-ins were loaded successfully where previously it didn't

<img width="282" alt="o365-yo-6" src="https://user-images.githubusercontent.com/19200702/77710018-c5a73700-7031-11ea-849f-4811ab3af308.PNG">

**Comment by TCourtneyOwen** [comment] 2020-03-27 00:51
But custom functions still don't work? Have you tried =contoso.add(1,2) for example?

**Comment by georgek01** [comment] 2020-03-27 00:54
Correct, they do not work. I tried =contoso.add(1,2) and the cell displays #Busy! The task pane code does work however.

**Comment by georgek01** [comment] 2020-03-27 01:03
All the CONTOSO functions are available so the runtime was able to get the list from the manifest/code

<img width="389" alt="o365-yo-8" src="https://user-images.githubusercontent.com/19200702/77710708-a3161d80-7033-11ea-902e-da8fb056b115.PNG">

**Comment by georgek01** [comment] 2020-03-27 01:33
As mentioned earlier, it seems to be an identical issue as #159

**Comment by TCourtneyOwen** [comment] 2020-03-27 01:41
@georgek01 I have started a thread internally with a few folks who worked on the custom functions feature. They may chime in on this thread - either way I will get back to you tomorrow. Thanks for your patience,

-Courtney

**Comment by georgek01** [comment] 2020-03-27 01:43
@TCourtneyOwen Thank you for your assistance

**Comment by shyambhiogade** [comment] 2020-03-27 03:18
just to let you know that I am also facing the exactly same problem, my custom function was working some days back attached demo app and excel version detail
![image](https://user-images.githubusercontent.com/10468130/77717953-e2def580-6f9e-11ea-87a1-67ad75ce76f0.png)

[demo custom function.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/4391286/demo.custom.function.zip)

**Comment by TCourtneyOwen** [comment] 2020-03-27 16:18
@georgek01 @shyambhiogade Can you please try the following:

Open Excel (don't worry about running "npm start" - just boot Excel)
Go to Insert --> Get Addins in the ribbon
In the Addin Store, search for WA104381692 and click Add to insert the addin

This will give you additional custom functions.  Try entering a custom function such as the following:
=CFSample.GET_DAY()

Is this doesn't work, then it clearly has to be a problem with the custom functions runtime and not the yo office template (I think this is more likely the case, but it would be helpful to confirm)

**Comment by shyambhiogade** [comment] 2020-03-27 16:40
it worked fine. i have given you my test application can you please check, its just the standard sample application.

**Comment by TCourtneyOwen** [comment] 2020-03-27 16:46
@shyambhiogade I don't see any link to your test application?

**Comment by shyambhiogade** [comment] 2020-03-27 16:48
@TCourtneyOwen  please give me your app please, https://github.com/OfficeDev/Excel-Custom-Functions/files/4391286/demo.custom.function.zip this is the link, also looks like I missed polyfill js to include in HTML , even after that it's not working.

**Comment by TCourtneyOwen** [comment] 2020-03-27 18:00
@shyambhiogade I am indeed hitting the same error when using your project. I don't hit any errors however when creating a new custom functions project with yo office.  I am looking into what's different in your project (e.g. I see you are using gulp, but I doubt that's the issue)

**Comment by shyambhiogade** [comment] 2020-03-27 18:12
@TCourtneyOwen let me know you need any other question from me

**Comment by TCourtneyOwen** [comment] 2020-03-27 18:31
@ShellyShulei two things jumped out at me.  In functions.html, you have the following:
<script src="https://localhost:5555/ExcelAddin/functions.js" type="text/javascript"></script>. I commented this out.  I then noticed that functions.ts has been customized. If I replace the content of functions.ts with the default content generated by yo office, run "npm run build" and 'npm start" everything works fine.  So it's one or both of these issues causing problems

**Comment by dabbara-geetha** [comment] 2020-03-27 19:19
I'm also facing the same issue as @ShellyShulei .  I tried sample applications from github/officeDev none of them are working in desktop excel. 
Details:
platform - Laptop
Office Excel version - 2016 MSO (16.0.4266.1001)
Browser - Chrome (Working in excel online)

@TCourtneyOwen  - As per your comment, I inserted  WA104381692  add-in from the store, When I tried =CFSample.GET_DAY(), I'm getting #NAME? error in the cell.
I have tried clearing the excel cache as well.
Please suggest its issue custom function runtime.

**Comment by shyambhiogade** [comment] 2020-03-27 19:40
geetha, i think you are not matching the minimum version required for the custom function to work

**Comment by shyambhiogade** [comment] 2020-03-27 20:09
@TCourtneyOwen i took a fresh copy and ran using dev server and it worked, we also have our own server in IIS and in aspnet.core, what is what I was trying. thanks for your help, its good now. i am not able to debug though

**Comment by dabbara-geetha** [comment] 2020-03-27 20:09
@shyambhiogade  - I have added below requirement set in manifest.xml 
 <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>

**Comment by dabbara-geetha** [comment] 2020-03-27 20:14
@TCourtneyOwen - I'm getting below error while using CFSAMPLE.

![image](https://user-images.githubusercontent.com/62707899/77796608-027d2900-7046-11ea-848a-e296a51d06f0.png)

any suggestions on this?

**Comment by shyambhiogade** [comment] 2020-03-27 20:33
is excel version good to run a custom function

**Comment by dabbara-geetha** [comment] 2020-03-27 20:36
I'm going through the issue - https://github.com/OfficeDev/Excel-Custom-Functions/issues/158

I have MS office 2016. Does custom function work only with MS office 365? 
![image](https://user-images.githubusercontent.com/62707899/77798282-f47cd780-7048-11ea-9d44-6983c11755a7.png)

**Comment by georgek01** [comment] 2020-03-27 20:40
@TCourtneyOwen  I ran **=CFSample.GET_DAY()** from **WA104381692**. It took a while but finally returned **Saturday**

**Comment by dabbara-geetha** [comment] 2020-03-27 20:45
@georgek01 - Could you share your MS Excel product information?
 I'm using MS office standard 2016,  =CFSample.GET_DAY() is not working for me.
Thanks in advance.

**Comment by georgek01** [comment] 2020-03-27 20:46
My setup is:

Office Version : 18.2002.1101.0 (Office 365 Home Edition)
OS Version: 1909 (Build 18363.720)
Node Version: 10.14.2

**Comment by dabbara-geetha** [comment] 2020-03-27 20:49
It seems to be custom functions works only with Office 365 but not for Office standard desktop app.

**Comment by shyambhiogade** [comment] 2020-03-27 20:51
geetha, please click on about excel and print that screen here, its supported on excel desktop just that you need to have right build.

**Comment by dabbara-geetha** [comment] 2020-03-27 20:57
![image](https://user-images.githubusercontent.com/62707899/77799834-fdbb7380-704b-11ea-87fb-601a41e3cc06.png)

**Comment by shyambhiogade** [comment] 2020-03-27 21:00
you need to update your excel, the following is the supported build 
![image](https://user-images.githubusercontent.com/10468130/77800049-4fa3cf80-7033-11ea-947f-0d54805c93c0.png)

**Comment by georgek01** [comment] 2020-03-27 21:01
@TCourtneyOwen I clicked the **Show CFSample Taskpane** button again and tried the RAND function. Now it does not work :(

<img width="780" alt="ms-sample-1" src="https://user-images.githubusercontent.com/19200702/77800147-0c9d3700-70db-11ea-8316-bfeaf5326f68.PNG">

**Comment by georgek01** [comment] 2020-03-27 21:02
Oh wait, it needs a parameter!

**Comment by georgek01** [comment] 2020-03-27 21:02
It does work :)

**Comment by dabbara-geetha** [comment] 2020-03-27 21:13
@shyambhiogade  - I see it is mentioned as **_connected to office 365 subscription_**. Mine is a standalone desktop version. MS office standard 2016.

**Comment by weshi** [comment] 2020-03-28 00:59
@georgek01 Just to confirm, is your own add-in working now, or it still have issues?

**Comment by georgek01** [comment] 2020-03-28 01:04
@weshi My own add-in does not work. The one I installed (WA104381692) does work however.

**Comment by georgek01** [comment] 2020-03-28 01:05
Have you guys made changes? Should I try and create an add-in again?

**Comment by weshi** [comment] 2020-03-28 02:15
@georgek01 as far as I know, no change have been made recently. Can I try your add-in? Do you have your manifest shared somewhere? Or, is your add-in shared on GitHub or somewhere?

**Comment by georgek01** [comment] 2020-03-28 02:25
@weshi It's the add-in generated from running yo office and selecting **custom function** and **JavaScript**. I have not made any changes when I experience the issue.

[test3-add-in.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/4396529/test3-add-in.zip)

[manifest.txt](https://github.com/OfficeDev/Excel-Custom-Functions/files/4396523/manifest.txt)

**Comment by weshi** [comment] 2020-03-28 03:50
Thanks @georgek01 

I checked your files, they are all the default files from the project template. I also tried to create a new project with YO, and it works correctly on my side. It's hard to know what is the root cause that your own addin does not work, while the one from the store works. 

I suspect that there might be something related to out-of-date cache. if you like, could check below:

1) Clean the cache folder for your add-ins (they will be recreated once add-ins are reinstalled again). Here are the steps:

- Go to %:\Users<user_name>\AppData\Local\Microsoft\Office\16.0\Wef
- Delete all the content in the WEF folder

2) Check your registry (run regedit to open the Registry Editor): Check under below path to find the item for your add-in and remove it.

Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Wef\Developer

For example, on my box, it looks like this:

![image](https://user-images.githubusercontent.com/11494417/77814108-1ded4000-70e9-11ea-865c-dd5fb4d5dc3d.png)

3) Restart your add-in:
- Return to your custom functions folder and run "npm start" again.

4) Open your browser and check if your local http server are running correctly. In your case, these files should be accessible from browser (your Excel desktop client will also be automatically opened and add-in will be reinstalled).

- https://localhost:3000/functions.js 
- https://localhost:3000/functions.html
- https://localhost:3000/taskpane.html

5) Check if your add-in or Excel status bar say any error happened (if everything works correctly, it should say the add-in and the functions are installed correctly).

6) Try to enter a formula at any cell in your Excel spreadsheet such as =CONTOSO.CLOCK(), and see if it set the correct value in the cell. 

If it does not work, please make a video or screen shot for step 4-6 and send to me. We will do further investigation.

(BTW, please be aware that Custom Functions are only enabled for users with Office 365 license. But you should have it as you said the CFSample add-in works in your case.)

**Comment by georgek01** [comment] 2020-03-29 00:27
@weshi Here is the steps I completed:

- Cleared the wef folder. On my machine it is located at
`C:\Users\georg\AppData\Local\Packages\Microsoft.Office.Desktop_8wekyb3d8bbwe\LocalCache\Local\Microsoft\Office\16.0\Wef`

![image](https://user-images.githubusercontent.com/19200702/77836595-76d9d880-71bc-11ea-9814-5187c2b0f24a.png)

- Cleared the **Wef\Developer** registry path but left the **Developer\RuntimeLogging** intact

![image](https://user-images.githubusercontent.com/19200702/77836589-5e69be00-71bc-11ea-89ae-36f2dd724283.png)

- From VS Code I ran **npm update**, **npm run build**

![image](https://user-images.githubusercontent.com/19200702/77836645-d7691580-71bc-11ea-9e0f-0d40e4afb512.png)

- From VS Code I ran **npm start**

![image](https://user-images.githubusercontent.com/19200702/77836675-14cda300-71bd-11ea-98b8-2d9b0296995a.png)

![image](https://user-images.githubusercontent.com/19200702/77836693-2dd65400-71bd-11ea-834b-98848070c4aa.png)

![image](https://user-images.githubusercontent.com/19200702/77836702-434b7e00-71bd-11ea-9f64-79d1d0ae10f8.png)

![image](https://user-images.githubusercontent.com/19200702/77836715-66762d80-71bd-11ea-9919-c4416959c67e.png)

![image](https://user-images.githubusercontent.com/19200702/77836724-7f7ede80-71bd-11ea-9839-cb2d677b1467.png)

- From Excel, I click the Taskpane button to open the add-in. The taskpane code  runs fine

![image](https://user-images.githubusercontent.com/19200702/77836746-c2d94d00-71bd-11ea-8ebd-4f6349e4fa56.png)

- The custom functions do not work however

![image](https://user-images.githubusercontent.com/19200702/77837015-a2f75880-71c0-11ea-94f5-6c4583d8f2ea.png)

Could it be because add-in **test3** is loaded twice? Even if I close the taskpane with the error it still does not work.

**Comment by georgek01** [comment] 2020-03-29 00:30
From the runtime logging file:

`29/03/2020 13:20:15	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin]		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
29/03/2020 13:20:15	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.ADD		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
29/03/2020 13:20:15	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.CLOCK		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
29/03/2020 13:20:15	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.INCREMENT		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
29/03/2020 13:20:15	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.LOG		
29/03/2020 13:20:15	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success]		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Installation] [Functions] [Begin] Solution=b05854fb-5f65-4a06-824a-9659e617ded0, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.ADD, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.CLOCK, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.CLOCK, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.LOG, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSO.LOG, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:20:15	Medium	CustomFunctions	[Installation] [Functions] [End] [Success] Solution=b05854fb-5f65-4a06-824a-9659e617ded0, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:21:49	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:21:55	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.CLOCK, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:22:03	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.INCREMENT, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:22:13	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.LOG, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:22:35	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
29/03/2020 13:22:35	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.LOG, Workbook=Excel add-in b05854fb-5f65-4a06-824a-9659e617ded0.xlsx		
`

**Comment by georgek01** [comment] 2020-03-29 00:34
I'm also able to debug the taskpane JS code

![image](https://user-images.githubusercontent.com/19200702/77837138-0afa6e80-71c2-11ea-846d-c94009e2ce2d.png)

**Comment by georgek01** [comment] 2020-03-29 00:46
Using **Script Lab** I'm able to create the functions I require from an add-in.

![image](https://user-images.githubusercontent.com/19200702/77837252-87da1800-71c3-11ea-8d13-e0ca19925e6c.png)

**Comment by shyambhiogade** [comment] 2020-03-29 21:38
@TCourtneyOwen hi again, i have my web server developed in asp.net core, when i keep this addin files under that server and try to access the web api, i dont get the expected result, but if i write same function on a button actoin in html and try to load in browser i get proper result, do you know if i need to do anything specific.

**Comment by georgek01** [comment] 2020-03-29 21:55
@shyambhiogade Is it not a CORS issue? I had a similar problem and had to allow any/specific domain to access my API.

**Comment by georgek01** [comment] 2020-03-29 21:57
@shyambhiogade I also found **localhost** to be problematic (I received a network error) hence I created an Azure hosted API for testing.

**Comment by shyambhiogade** [comment] 2020-03-29 22:12
@georgek01 i dont think this is cors issue, as when i try to access same api from sample application which runs on https://localhsot:3000, it works fine, but only when i copy all files in dist folder to my local server, it does not work, other function in sample application such as add works fine so there is no problem with respect to local custom function, issue comes only when i try make a web api call to my server

**Comment by georgek01** [comment] 2020-03-29 22:27
@shyambhiogade To get custom functions to work, did you just update your version of Excel?

**Comment by shyambhiogade** [comment] 2020-03-29 22:29
no it was working, problem is just with XMLHttpRequest request to my server

**Comment by georgek01** [comment] 2020-03-29 22:32
Is your server end-point HTTPS? Runing the server from Node ensures the required cert is installed. You may need to install a cert on your dev server too.

**Comment by TCourtneyOwen** [comment] 2020-03-29 23:38
Exactly what I was going to point out. It needs to be https with valid certs installed.

**Comment by shyambhiogade** [comment] 2020-03-29 23:47
my server end-point is http not https, are you saying to be able to use custom function-it should be https, our application is intranet application and there is complication in providing the cert on customer machine. also it would be nice if there was any demo on how to debug, i have that custom function sample, and when i run it from vscode to debug, debugging just does not work even with simple add function.

**Comment by weshi** [comment] 2020-03-30 01:33
@georgek01 Thanks for the detail information. I'm curious why there are two test3 add-in loaded. Do you have two add-ins with the same name and id?

If possible, we can have a Microsoft Teams meeting so that we can look at together. Please let me know what time is good to you. I'm located in Beijing (UTC+08 timezone). Thanks.

**Comment by georgek01** [comment] 2020-03-30 01:36
@weshi That is the add-in that starts when I start debugging - npm start. So it's the add-in that I'm running at the time. To then run the Taskpane code, I click the button in the ribbon that was also created when I started debugging. So no, I do not have two installed.

**Comment by georgek01** [comment] 2020-03-30 01:41
I'm available anytime today after 11:00am your time. I'm UTC+12 (so we close)

![image](https://user-images.githubusercontent.com/19200702/77867573-4ebda880-7294-11ea-92a5-30aeb398db6c.png)

**Comment by weshi** [comment] 2020-03-30 02:23
@georgek01 I have send out the meeting request. Let's discuss more at the meeitng.

@ShellyShulei could you try to add http://localhost:32569 to your AppDomain and retry again?

<AppDomains>
    <AppDomain>contoso.com</AppDomain>
    <AppDomain>http://localhost:32569</AppDomain>
  </AppDomains>

**Comment by georgek01** [comment] 2020-03-30 03:54
My issue has been resolved!

When I initially installed Office it was through the Store. This time I installed Office from my account (https://account.microsoft.com/services/office/install) and now custom functions work.

Not sure why the behavior is different as both versions have the same build.

@weshi, thank you to you and your team for your assistance.

![image](https://user-images.githubusercontent.com/19200702/77873580-de6c5280-72a6-11ea-9f80-d5f19a95a922.png)

**Comment by shyambhiogade** [comment] 2020-03-30 04:36
@weshi i have added localhost in app domain, can we have a call on team, skype, zoom let me know.

**Comment by weshi** [comment] 2020-03-30 07:36
@shyambhiogade I didn't find your email in your profile. Please let me know and I can send out a Teams meeting schedule. Thanks.

**Comment by shyambhiogade** [comment] 2020-03-30 15:08
shyam.bhiogade@gmail.com is my email id.

**Comment by weshi** [comment] 2020-03-30 23:31
Thanks @shyambhiogade 
I have sent out the meeting invitation.

**Comment by shyambhiogade** [comment] 2020-03-30 23:34
thanks received it and accepted

**Comment by dabbara-geetha** [comment] 2020-03-31 15:48
Hi,

I've hosted my custom excel add-in to azure website, added web.config as well and updated website url in the manifest.  After uploading this manifest to excel online, custom functions are not working but taskpane is showing. 
Is there any problem with azure hosting? please suggest. 
Below is the web.config 
<?xml version="1.0"?>
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
			 <mimeMap fileExtension=".map" mimeType="application/octet-stream" />
     </staticContent>
    </system.webServer>   
</configuration> 

I tried hosted the same build to github, then the custom functions are working

**Comment by weshi** [comment] 2020-04-01 03:53
@shyambhiogade  I've sent an email to you with the solution to the issue you have seen. Basically if you are not using the YO office generator and npm start to sideload/debug your add-in hosted on localhost host, you have to make sure you create the similar registry entry for your add-in, and set the UseDirectDebugger key item set to 1. 
![image](https://user-images.githubusercontent.com/11494417/78097594-4342bc80-740f-11ea-9dfc-24f674c72323.png)

![image](https://user-images.githubusercontent.com/11494417/78097656-67060280-740f-11ea-9502-b7e093e892b7.png)

Otherwise you cannot access the resource on your localhost server with XmlHttpRequest from your custom functions.

**Comment by weshi** [comment] 2020-04-01 03:58
@dabbara-geetha Could you please share more information about your environment? What is the error/value you see returned from the custom function formula? Have you added your domain on azure website to your manifest? Share some log would also be helpful.
If needed, I can have a Microsoft Teams meeting to discuss with you.

**Comment by dabbara-geetha** [comment] 2020-04-01 12:54
@weshi - Thank you for the response
Environment details - Windows 10 OS, laptop, Office 365 Excel online.
I've added the Azure website in the manifest file. The issue is I don't see my custom functions in the functions tab when I type =[myFunctionName]
![image](https://user-images.githubusercontent.com/62707899/78139269-38c7f900-73f6-11ea-8e53-04805b9e3aa2.png)
I will configure Azure app service logs
I have opened a separate Github issue to address this issue - https://github.com/OfficeDev/Excel-Custom-Functions/issues/200

**Comment by RuoyingLiang** [comment] 2020-04-02 03:24
The issue in this thread has been resolved. So close this thread.

**Closed by RuoyingLiang** 2020-04-02 03:24 UTC
Labels: Area: Excel, Needs: attention :wave:, Type: discussion
