### ISSUE TITLE
Evaluating a basic custom function in Excel online takes a long time

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/Excel-Custom-Functions#223] opened 2020-07-24 20:48 UTC
# Expected behavior

Prior to this week, when our team first noticed this behavior, evaluation would be nearly instantaneous.

# Current behavior

After entering/changing a cell with a custom function in Excel on the web, the cell shows #BUSY and the "calculating" progress bar appears for a long time, around 5-10 seconds, before the result is returned.  

![image](https://user-images.githubusercontent.com/34104510/88433382-f32ba380-cdcb-11ea-9a20-58c972e63f34.png)

I've seen this occur with the sample "spherevolume" function in Script Lab, but it also occurs with the custom function in our add-in.

## Steps to Reproduce

1. In Script Lab, open the Basic custom function sample (with the spherevolume function)
2. Run the sample to register the function
3. Enter a spherevolume formula on the worksheet, e.g. `=SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME(7)`

This is when the delay occurs.  The delay varies in length.  Sometimes it's only a second or two, but it can run over 10 seconds.

## Context

Using Excel online (Office Developer license) in Chrome

## Failure Logs

No errors or other messaging in the Chrome dev tools console.

**Comment by RuoyingLiang** [comment] 2020-07-27 07:37
Thanks for reporting. We are looking into this issue.

**Comment by RuoyingLiang** [comment] 2020-07-27 10:17
We found the root cause and working on it. Will update this thread once it's fixed.

**Comment by keyur32** [comment] 2020-07-30 01:27
Updated label as fix has been deployed and closing out.

**Closed by keyur32** 2020-07-30 01:27 UTC
Labels: Status: fixed
